spring.application.name=budgeting
spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.chat.options.response-format.type=TEXT

logging.level.org.springframework.ai=DEBUG

spring.ai.model.audio.transcription=openai
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.temperature=0 
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.prompt=O áudio contém transações financeiras em português do Brasil. Transcreva todos os valores monetários em Real brasileiro, usando o símbolo R$ e vírgula decimal. Quando nenhuma outra moeda for mencionada, considere BRL. Exemplos: cinquenta reais = R$ 50,00; vinte reais e cinquenta centavos = R$ 20,50, o numero tem que ser salvo no banco de dados em bigDecimal.

spring.ai.model.audio.speech=openai
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.voice=nova
spring.ai.openai.audio.speech.options.speed=1.2
spring.ai.openai.audio.speech.options.response-format=mp3

spring.datasource.url=jdbc:mysql://127.0.0.1:3305/transaction
spring.datasource.username=app
spring.datasource.password=app
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


